added application Id to the audit call
hmrc/identity-verification-questions pull request #63
Opened 2024-07-30 15:13 UTC by SeanMurray1

2024-07-31 08:45 UTC, ChrisHillCap requested changes
Can we have tests for this please

2024-07-31 10:04 UTC, DarylMConway approved these changes
LGTM

2024-07-31 10:06 UTC, DarylMConway commented
sorry didn't see the request changes from Chris, ignore my approval

2024-08-12 10:34 UTC, woollett-r commented on it/test/monitoring/AuditServiceISpec.scala
> +      (multifactorAuthenticationCheckAuditRecord \ "detail").validate[Selection] match {
I think it would be better to create a custom class here and test all attributes similar to what you have done with IdentityVerificationAnswer.

2024-08-12 10:40 UTC, woollett-r requested changes
I think we should update the integration test for CircuitBreakerUnhealthyService to test all attributes.

2024-08-14 14:29 UTC, SeanMurray1 commented
test please

2024-08-14 14:30 UTC, SeanMurray1 commented
please test

2024-08-14 14:30 UTC, SeanMurray1 commented
test this please

2024-08-14 14:40 UTC, SeanMurray1 commented
test this please

2024-08-14 16:14 UTC, woollett-r approved these changes

2024-08-15 08:31 UTC, ChrisHillCap approved these changes

2024-08-15 09:28 UTC, merged